# Generated by Django 4.2.6 on 2023-11-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField(default='')),
                ('owner', models.TextField(default='')),
                ('lexicon_id', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('member', models.TextField(default='')),
                ('ready', models.TextField(default='')),
                ('round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('password', models.TextField(default='', max_length=32)),
                ('token', models.TextField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Work_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField(default='')),
                ('round', models.IntegerField(default=0)),
                ('username', models.TextField(default='')),
                ('category', models.IntegerField(default=0)),
                ('img', models.TextField(default='')),
                ('word', models.TextField(default='')),
            ],
        ),
    ]
