# Generated by Django 4.2.6 on 2023-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_round_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField(default='')),
                ('answer_seq', models.TextField(default='')),
                ('approval', models.IntegerField(default=0)),
                ('disapproval', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='work_info',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='work_info',
            name='disapproval',
        ),
    ]
